takescourse(X,15739)
memberof(X,Y), undergraduatedegreeFrom(X,Y), suborganizationof(Z,Y)
publicationauthor(X,61400)
worksfor(X,4002), name(X,Y), emailaddress(X,Z), telephone(X,W)
memberof(X,4002)
takescourse(X,Y), teacherof(74207,Y)
memberof(X,Y), suborganizationof(Y,33544), undergraduatedegreeFrom(X,Z)
advisor(X,Y), teacherof(Y,Z), takescourse(X,Z)
takescourse(X,15739)
suborganizationof(X,33544)
worksfor(X,Y), suborganizationof(Y,33544)
t(X,5)
