takescourse(X, http://www.Department0.University0.edu/GraduateCourse0)
memberof(X, Y), undergraduatedegreefrom(X, Y), suborganizationof(Z, Y)
publicationauthor(X, http://www.Department0.University0.edu/AssistantProfessor0)
worksfor(X, http://www.Department0.University0.edu), name(X, Y), emailaddress(X, Z), telephone(X, W)
memberof(X, http://www.Department0.University0.edu)
takescourse(X, Y), teacherof(http://www.Department0.University0.edu/AssociateProfessor0, Y)
memberof(X, Y), suborganizationof(Y, http://www.University0.edu), undergraduatedegreefrom(X, Z)
advisor(X, Y), teacherof(Y, Z), takescourse(X, Z)
takescourse(X, http://www.Department0.University0.edu/GraduateCourse0)
suborganizationof(X, http://www.University0.edu)
worksfor(X, Y), suborganizationof(Y, http://www.University0.edu) 